### ISSUE TITLE
no Accept: text/html

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/picstar#1]
If the Accept Header is `text/html` it should redirect to index.html into public/dist folder. 

Up to now it is just `application/json`

**Comment by abisz** [comment]
after hours of researching I changed the routes for the api by prepending api/\* for all api-routes. For every other request I return the public/dist/index.html as a view. 

!! Important !!
when returning the view you have to be careful with relative paths inside your code. The site will run inside the public folder not the dist!!!

**Comment by JPeer264** [comment]
Works perfectly, thanks!
