### ISSUE TITLE
Check login

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/picstar#2]
Yesterday I tried to check if the user is logged in as follows:

Accept: application/json
Method: POST
URL: localhost/api/login
DATA: token={tokenvalue}

Is there a way to check this like that?

**Comment by abisz** [comment]
Login doesn't require a token, just the email and password. Then the token will be returned.
For every other request that needs a token, it must look like this:

Authorization: Bearer {tokenvalue}

**Comment by abisz** [comment]
@JPeer264 haha wtf, are you still working on this?

**Comment by JPeer264** [comment]
no was just cleaning up my issue view ;)
